# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
success_symbol = "âœ"     # The "symbol" segment is being set to "âœ"
error_symbol = "âœ—"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
ssh_only = true

[cmd_duration]
min_time=8000
disabled = true

[directory]
truncation_length=0
truncate_to_repo=false
read_only = "ğŸ”’"

[python]
format = 'via [${symbol}${pyenv_prefix}${version} (\($virtualenv\) )]($style)'
symbol = ""

[custom.mojo]
symbol = "ğŸ”¥"
command = """
if [[ -n $CONDA_PREFIX ]]; then
  mojo --version | awk '{print "ğŸª„ " $2}'
else
  mojo --version | awk '{print $2}'
fi
"""
detect_files = ["magic.lock"]
detect_folders = [".magic"]
detect_extensions = ["ğŸ”¥", "mojo"]
format = '[[ $symbol ($output) ](fg:base bg:teal)]($style)'
style = "bg:teal"

[nodejs]
disabled=true

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
